### ISSUE TITLE
Filter Option: Public Servers with Open Registration

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica-directory#11]
It would be great to have on this page: https://dir.hubup.pro/servers a switch that toggles between all servers and only those with Open registration.

**Comment by MrPetovan** [comment]
Wow, you were quick to deploy the new version! To answer your question, I don't think it's the goal of the directory to expose all the servers and profiles, only those that people can actually interact with. For example, there would be no use listing my own node as it isn't accepting registrations, but there is a use displaying my profile because I elected to be added to the directory.

The planned stats page (#2) will give a snapshot of the total number of servers in the Friendica network without having to reveal information about closed nodes.

**Comment by AndyHee** [comment]
So all the public servers listed are Open Registration? That's fine and what I was hoping for.

I think I saw several that were closed. Let me recheck this.

**Comment by MrPetovan** [comment]
Yes, the "Public Servers" view should only show `register_policy = OPEN_REGISTRATION`.

**Comment by AndyHee** [comment]
Great!

I close this now.
