### ISSUE TITLE
Support: Main directory seems to lose more and more users

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica-directory#45]
The main Friendica directory at https://dir.friendica.social/ seems to lose users by the hour.

There were more than 3000 listed users some weeks ago. Today only 1300 are listed. The same applies to the forum users.

Maybe it is an issue with the directory itself or we changed something in Friendica that drains the directory somehow.

On my own directory instance I see a decline in listed users too. But not that much (3000 -> 2500).

Edit: 2020-07-17 updated user count on my directory instance: 1549 users (-1000)

**Comment by MrPetovan** [comment]
Bleh.

**Comment by AndyHee** [comment]
My directory has lost all it's servers/ users.

https://dir.hubup.pro/stats

**Comment by MrPetovan** [comment]
We identified an issue with Friendica where the public key isn't returned when the profile is polled, and it is one of the required field for a profile to be considered valid. The Friendica part of this issue has been fixed in https://github.com/friendica/friendica/pull/9287, but I am working on removing this unnecessary check in the directory code.
