### ISSUE TITLE
Data will not be updated

### ISSUE THREAD

**Issue by Tealk** [friendica/friendica-directory#74]
Hello,

the data of my server is not displayed correctly in the list since one week. The name is not correct and also the description is empty.
![image](https://user-images.githubusercontent.com/12276250/120476219-9cf39d80-c3aa-11eb-8958-f2a45702f19a.png)

**Comment by MrPetovan** [comment]
Directory data shows that your server was last polled on June 2nd at 00:26 GMT. The next poll is planned on June 4th at 14:56 GMT and it's possible that the directory failed to retrieve your node data since it shows a retries count of 5. I'll try to poll it manually.

**Comment by MrPetovan** [comment]
I see you moved your server from `friendica.rollenspiel.monster` to `rollenspiel.group`, it confused the directory since it independently found the new domain and now it can't update the correct record between both. I fixed the data manually and ran the poll again, data looks good now.

Thank you for reaching out!

**Comment by Tealk** [comment]
Thanks for your quick help
